language: JAVA
script: ./gradlew build check -i -s
jdk:
  - openjdk8
cache:
    directories:
    - .autoconf
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
env:
  global:
    - JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64